# Generated by Django 3.0.5 on 2021-02-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
